UIBULKED-298: Group Item record properties using optgroup component
folio-org/ui-bulk-edit pull request #334
Opened 2023-06-29 11:41 UTC by UladzislauKutarkin

## Purpose

[UIBULKED-298](https://issues.folio.org/browse/UIBULKED-298)
## Approach

#### TODOS and Open Questions

## Learning

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [ ] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2023-06-29 11:42 UTC, UladzislauKutarkin commented
https://github.com/folio-org/ui-bulk-edit/assets/72550466/5d77a31b-1a3d-41f9-bdc2-17281f1f247f

2023-06-29 14:01 UTC, zburke requested changes
The `renderOptions` function itself looks good but the `category` attribute of the updated `getItemsOptions` elements must be i18n'ed. 

Please obey lint instead of turning it off :)

2023-06-30 11:05 UTC, UladzislauKutarkin commented on src/constants/selectOptions.js
> +    category: 'Location',
fixed

2023-06-30 11:05 UTC, UladzislauKutarkin commented on src/constants/selectOptions.js
> +    category: 'Location',
fixed

2023-06-30 11:05 UTC, UladzislauKutarkin commented on src/constants/selectOptions.js
> +    category: 'Loan type',
fixed

2023-06-30 11:05 UTC, UladzislauKutarkin commented on src/utils/filters.js
> +  // eslint-disable-next-line guard-for-in
I agree, I fixed as eslint expecting it.

2023-06-30 14:33 UTC, zburke approved these changes

2023-07-05 07:28 UTC, vashjs approved these changes

2023-07-07 07:13 UTC, merged