UIBULKED-338 Add calculation of previews height based on content
folio-org/ui-bulk-edit pull request #453
Opened 2024-01-10 11:20 UTC by vashjs

2024-01-10 16:16 UTC, BogdanDenis requested changes

2024-01-10 16:16 UTC, BogdanDenis commented on src/components/BulkEditList/BulkEditListResult/Preview/ErrorsAccordion/ErrorsAccordion.test.js
> +import { act, logDOM, render, screen, waitFor } from '@testing-library/react';
Please remove unused `logDOM` import

2024-01-10 23:54 UTC, vashjs commented on src/components/BulkEditList/BulkEditListResult/Preview/ErrorsAccordion/ErrorsAccordion.js
> +          {!!errorLength && (
Thanks for pointing it out, I removed this condition at all because it's not required anymore.

2024-01-11 07:49 UTC, artem-blazhko approved these changes

2024-01-11 08:52 UTC, UladzislauKutarkin approved these changes

2024-01-11 09:17 UTC, merged