UIBULKED-571 Errors in response to UI calls
folio-org/ui-bulk-edit pull request #661
Opened 2024-12-10 10:09 UTC by vashjs

Based on the new requirements, for all non bulk-operation modules to which the UI makes requests, errors should be generated according to the following template:

`<module-name> returns  status code: <status-code> - <error details>. `

Since some models do not have a message and the message consists only of a status code, additional logic has been added for such cases. Depending on the specific case, a basic HTTP error will be shown based on the dictionary from `http-status-codes` library.

Refs: [UIBULKED-571](https://folio-org.atlassian.net/browse/UIBULKED-571)

2024-12-11 13:53 UTC, UladzislauKutarkin approved these changes

2024-12-17 22:05 UTC, JohnC-80 requested changes
We can do better than the static lists contained in this - HTTP codes/messages or UI module names... as the capabilities of bulk-edit increase, the static list of module names would have to be updated. Blocking until further PO feedback is obtained.

2024-12-20 17:37 UTC, JohnC-80 reviewed
A static npm library is better than keeping the `code : message` mapping in our own code, but only just so. If this information is intended for developers to fix the issue, a lack of an error response from the server is most definitely an issue - but that isn't helped if an error message is contrived by the UI. UI modules should not make up for the shortcomings of backend modules.
FOLIO generally keeps a separation between the UI and the backend via interface - this said, backend modules can change without the UI caring, so long as the same interface is still provided. Now with the static list in place, the UI for Bulk Edit has to concern itself with potential changes. Future developments will see if we can make this functionality more dynamic... until then, here we are.

2024-12-24 12:46 UTC, Dmytro-Melnyshyn approved these changes

2024-12-24 14:19 UTC, merged